# Generated by Django 5.2.6 on 2025-11-08 07:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hero_title', 'Hero Section Title'), ('hero_subtitle', 'Hero Section Subtitle'), ('about_text', 'About Section Text'), ('contact_info', 'Contact Information'), ('meta_description', 'Meta Description'), ('footer_text', 'Footer Text'), ('announcement', 'Site Announcement')], help_text='Type of content', max_length=50, unique=True)),
                ('content', models.TextField(help_text='Content text')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this content is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this content was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this content was last updated')),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Contents',
                'ordering': ['content_type'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team member name', max_length=100)),
                ('position', models.CharField(help_text='Job position', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('image', models.ImageField(blank=True, help_text='Team member photo', null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this team member is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name (letters, spaces, and periods only)', max_length=100, validators=[django.core.validators.RegexValidator(message='Name should only contain letters, spaces, and periods.', regex='^[a-zA-Z\\s\\.]+$')])),
                ('email', models.EmailField(help_text='Valid email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should only contain digits, +, -, spaces, and parentheses.', regex='^[\\d\\+\\-\\s\\(\\)]+$')])),
                ('message', models.TextField(help_text='Your message (10-2000 characters)', max_length=2000)),
                ('subject', models.CharField(default='General Inquiry', help_text='Subject of the message', max_length=200)),
                ('interest_area', models.CharField(choices=[('general', 'General Inquiry'), ('gk_textiles', 'GK Textiles'), ('gk_steels', 'GK Steels'), ('partnership', 'Partnership'), ('feedback', 'Feedback')], default='general', help_text='Area of interest', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether the message is archived')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the message was last updated')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='gk_group_ap_created_50f637_idx'), models.Index(fields=['is_read'], name='gk_group_ap_is_read_ea5c8c_idx'), models.Index(fields=['interest_area'], name='gk_group_ap_interes_5faf18_idx'), models.Index(fields=['email'], name='gk_group_ap_email_295597_idx')],
            },
        ),
    ]
